name: "Run buildifier"
description: 'Action to run buildifier on changed build files'

inputs:
  filepaths:
    description: 'Optional space-separated list of file paths to check. If not provided, all bazel will be checked.'
    required: false
    default: >
      :(glob)**/BUILD
      :(glob)**/BUILD.bazel
      :(glob)**/WORKSPACE
      :(glob)**/WORKSPACE.bazel
      :(glob)**/MODULE.bazel
      :(glob)**/*.bzl

runs:
  using: "composite"
  steps:

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 2
        persist-credentials: false

    - name: Check formatting with buildifier
      id: buildifier-check
      shell: bash
      env:
        TARGET_SHA: ${{ github.event.before }}
        FILE_PATHS: ${{ inputs.filepaths }}
      run: |
        echo "Detecting changed Bazel files..."
        
        # Add this line to resolve the dubious ownership error
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
        BAZEL_PATTERNS="$FILE_PATHS"
        
        # Determine the correct base for the git diff
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          DIFF_BASE="HEAD~1"
          
          echo "Comparing changes from $DIFF_BASE to HEAD"
        
          GIT_DIFF_CMD="git diff -z --name-only --diff-filter=d $DIFF_BASE HEAD -- $BAZEL_PATTERNS"
    
          echo "Checking formatting of changed bazel files..."
          $GIT_DIFF_CMD | xargs -0 buildifier --mode=check -v
          
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          # Run on all files if this is a push event
          buildifier -r -v --mode=check $BAZEL_PATTERNS
        
        else
          echo "::error::Unsupported event type: ${GITHUB_EVENT_NAME}"
          exit 1
        fi
